# Text Mining Assignment - Tommaso Pessina - 961739

The aim of this assignment is to analyse the first thrilogy of the Star Wars saga and, since this would not be relevant in the classifican case, we will create a SMS Spam/Ham classifier.

First we should import the necessary package.

In [5]:
import pandas as pd
from nltk.corpus import stopwords 
import string
from sklearn.feature_extraction.text import CountVectorizer 
from sklearn.feature_extraction.text import TfidfVectorizer
import re
from nltk.tokenize import SyllableTokenizer
from nltk import word_tokenize 

From "nltk" download the necessary packages. NLTK is the most used (and suitable) package for TextMining or Natural Language Processing.

In [6]:
import nltk
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\tompe\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\tompe\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\tompe\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

Read the three Star Wars script file

In [7]:
fileIV = open('SW_EpisodeIVclean.txt', 'r')
LinesIV = fileIV.readlines()
fileV = open('SW_EpisodeV.txt', 'r')
LinesV = fileV.readlines()
fileVI = open('SW_EpisodeVI.txt', 'r')
LinesVI = fileVI.readlines()

In [8]:
LinesIV[1]

"We're doomed!\t\t\t\t\t\t\n"

Set "english" as language in order to get the english stopword and the punctuation for delete it from the text.

In [9]:
stop_words_en = stopwords.words("english") 

stop_words_en = stop_words_en + list(string.punctuation)
#stop_words_en

Tokenize each word of each line (for each text) and delete the stopwords

In [10]:
text1IV = []#list()
text1V = []#list()
text1VI = []#list()


for line in LinesIV:
    text1IV.append([w for w in nltk.word_tokenize(line.lower()) if w not in stop_words_en])
for line in LinesV:
    text1V.append([w for w in nltk.word_tokenize(line.lower()) if w not in stop_words_en])
for line in LinesVI:
    text1VI.append([w for w in nltk.word_tokenize(line.lower()) if w not in stop_words_en])    

Now we will delete the " and `

In [11]:
textIV =[] #list()
textV =[] #list()
textVI =[] # list()

for line in text1IV:
    textIV.append([w for w in line if w not in ["''",'``']])
for line in text1V:
    textV.append([w for w in line if w not in ["''",'``']])
for line in text1VI:
    textVI.append([w for w in line if w not in ["''",'``']])

In [12]:
textIV[2]

["'ll", 'escape', 'princess', 'time']

Tranform the list of sentences in a list of word

In [13]:
new_lIV = [i for b in map(lambda x:[x] if not isinstance(x, list) else x, textIV) for i in b]
new_lV = [i for b in map(lambda x:[x] if not isinstance(x, list) else x, textV) for i in b]
new_lVI = [i for b in map(lambda x:[x] if not isinstance(x, list) else x, textVI) for i in b]

Now we should delete the digits at the start of each senteces

In [14]:
l4 = str(new_lIV)
l5 = str(new_lV)
l6 = str(new_lVI)
digit4 = re.findall(r'\d+', l4)
digit5 = re.findall(r'\d+', l5)
digit6 = re.findall(r'\d+', l6)

corpus4 =[] #list()
for line in textIV:
    corpus4.append([w for w in line if w not in digit4])
    
corpus5 =[] #list()
for line in textV:
    corpus5.append([w for w in line if w not in digit5])
    
corpus6 = [] #list()
for line in textVI:
    corpus6.append([w for w in line if w not in digit6])

In [15]:
corpus4[46]

['traced', 'rebel', 'spies', 'link', 'find', 'secret', 'base']

Tranform the list of sentences in a list of word

In [16]:
StarWarsIV = [i for b in map(lambda x:[x] if not isinstance(x, list) else x, corpus4) for i in b]

StarWarsV = [i for b in map(lambda x:[x] if not isinstance(x, list) else x, corpus5) for i in b]

StarWarsVI = [i for b in map(lambda x:[x] if not isinstance(x, list) else x, corpus6) for i in b]

In [ ]:
StarWarsIV

### Bigrams
Now we will create bigrams, that are n-grams with n equals to two. They are group of two adjacency word and can be usefull in order to analyse which couple are more frequent.

In [28]:
bigramsIV = nltk.ngrams(StarWarsIV, n = 2)

In [29]:
bigramsV = nltk.ngrams(StarWarsV, n = 2)

In [30]:
bigramsVI = nltk.ngrams(StarWarsVI, n = 2)

In [ ]:
for grams in bigramsIV: 
    print (grams)

In [ ]:
for grams in bigramsV: 
    print (grams)

In [ ]:
for grams in bigramsVI: 
    print (grams)

#### Frequency distribution
Firstly we will create the frequency distribution for the bi-grams previously created in order to see if there are relevaent couples.

In [31]:
freq_bigrams_IV = nltk.FreqDist(bigramsIV)
freq_bigrams_IV

FreqDist({('ca', "n't"): 29, ("'ve", 'got'): 20, ("'re", 'going'): 19, ("n't", 'know'): 14, ("'m", 'going'): 13, ('let', "'s"): 12, ('luke', 'luke'): 12, ('obi-wan', 'kenobi'): 12, ('r2', 'unit'): 11, ('rebel', 'base'): 11, ...})

In [32]:
freq_bigrams_V = nltk.FreqDist(bigramsV)
freq_bigrams_V

FreqDist({('lord', 'vader'): 20, ('...', 'han'): 16, ('han', "'s"): 15, ('ca', "n't"): 15, ('threepio', 'oh'): 15, ("n't", 'know'): 13, ("'m", 'going'): 12, ('han', 'well'): 11, ('threepio', 'sir'): 11, ("'ve", 'got'): 10, ...})

In [33]:
freq_bigrams_VI = nltk.FreqDist(bigramsVI)
freq_bigrams_VI

FreqDist({('threepio', 'oh'): 20, ('master', 'luke'): 16, ('ca', "n't"): 15, ('dark', 'side'): 12, ('death', 'star'): 11, ('let', "'s"): 11, ('luke', "'s"): 11, ('gon', 'na'): 11, ('wo', "n't"): 9, ('threepio', 'artoo'): 8, ...})

Now, for each movie, we will count the frequency of each word

In [35]:
freqIV = nltk.FreqDist(StarWarsIV)
freqIV

FreqDist({"'s": 208, "n't": 175, '...': 145, "'re": 103, "'ll": 75, "'m": 75, 'going': 71, "'ve": 67, 'luke': 64, 'get': 61, ...})

In [36]:
freqV = nltk.FreqDist(StarWarsV)
freqV

FreqDist({'han': 196, 'luke': 157, 'leia': 130, "'s": 128, "n't": 118, '...': 116, 'threepio': 96, 'vader': 81, 'lando': 79, "'re": 63, ...})

In [37]:
freqVI = nltk.FreqDist(StarWarsVI)
freqVI

FreqDist({'luke': 156, 'han': 133, "'s": 97, "n't": 96, 'threepio': 94, '...': 87, 'leia': 72, 'vader': 61, 'emperor': 60, 'lando': 48, ...})

Now we will select the 10th most common word for each movie and bigrams

In [38]:
import collections
swIV = collections.Counter(freqIV).most_common(10)
swV = collections.Counter(freqV).most_common(10)
swVI = collections.Counter(freqVI).most_common(10)

swIV_bigrams = collections.Counter(freq_bigrams_IV).most_common(10)
swV_bigrams = collections.Counter(freq_bigrams_V).most_common(10)
swVI_bigrams = collections.Counter(freq_bigrams_VI).most_common(10)

We create a data frame whose column are the movies and the rows are the word-frequency

In [39]:
test = list()
test2 = list()
test3 = list()
testA = list()
test2B = list()
test3C = list()
for elem in swIV:
    s = "{} - {}".format(elem[0], elem[1])
    test.append(s)
for elem in swV:
    s = "{} - {}".format(elem[0], elem[1])
    test2.append(s)
for elem in swVI:
    s = "{} - {}".format(elem[0], elem[1])
    test3.append(s)
for elem in swIV_bigrams:
    s = "{} - {}".format(elem[0], elem[1])
    testA.append(s)
for elem in swV_bigrams:
    s = "{} - {}".format(elem[0], elem[1])
    test2B.append(s)
for elem in swVI_bigrams:
    s = "{} - {}".format(elem[0], elem[1])
    test3C.append(s)

In [40]:
d = {'swIV': test, 'swV': test2, "swVI":test3,'swIVbigrams': testA, 'swVbigrams': test2B, "swVIbigrams":test3C}
df = pd.DataFrame(data=d)

In [41]:
df

swIV            swV           swVI                 swIVbigrams  \
0    's - 208      han - 196     luke - 156          ('ca', "n't") - 29   
1   n't - 175     luke - 157      han - 133         ("'ve", 'got') - 20   
2   ... - 145     leia - 130        's - 97       ("'re", 'going') - 19   
3   're - 103       's - 128       n't - 96        ("n't", 'know') - 14   
4    'll - 75      n't - 118  threepio - 94        ("'m", 'going') - 13   
5     'm - 75      ... - 116       ... - 87          ('let', "'s") - 12   
6  going - 71  threepio - 96      leia - 72       ('luke', 'luke') - 12   
7    've - 67     vader - 81     vader - 61  ('obi-wan', 'kenobi') - 12   
8   luke - 64     lando - 79   emperor - 60         ('r2', 'unit') - 11   
9    get - 61       're - 63     lando - 48      ('rebel', 'base') - 11   

                 swVbigrams                swVIbigrams  
0    ('lord', 'vader') - 20    ('threepio', 'oh') - 20  
1       ('...', 'han') - 16    ('master', 'luke') - 16  
2        ('han', "'s") - 15         ('ca', "n't") - 15  
3        ('ca', "n't") - 15      ('dark', 'side') - 12  
4   ('threepio', 'oh') - 15     ('death', 'star') - 11  
5      ("n't", 'know') - 13         ('let', "'s") - 11  
6      ("'m", 'going') - 12        ('luke', "'s") - 11  
7      ('han', 'well') - 11         ('gon', 'na') - 11  
8  ('threepio', 'sir') - 11          ('wo', "n't") - 9  
9       ("'ve", 'got') - 10  ('threepio', 'artoo') - 8

We can notice that some of the most common bigrams actually rapresent charachter of the movie and most of the time they don't match the single word frequency distribution. So basically by counting each word and by counting bigrams we will obtain two different answer to different question.

### Clusterization
We choose to use the k-means cluster algorithm which will calculate the mean for each cluster and divide the observation in n cluster according to their distance (i.e. of each observation) from the mean of the clusters (i.e. it's centroid).  
Note that here we will use the TF-IDF vectorisation method on the array of lines and only of the Star Wars IVth movie for semplicity. The TF-IDF will simplify the clusterization process beacuse we will obtain a list of token without any stopword.

In [43]:
from sklearn.cluster import KMeans

In [44]:
vectorizer = TfidfVectorizer(stop_words='english')
X = vectorizer.fit_transform(LinesIV)

In [45]:
true_k = 4
model = KMeans(n_clusters=true_k, init='k-means++', max_iter=100, n_init=1)
model.fit(X)

KMeans(max_iter=100, n_clusters=4, n_init=1)

This portion of code will print, for each cluster, the first 10 element which belong to it

In [46]:
print("Top terms per cluster:")
order_centroids = model.cluster_centers_.argsort()[:, ::-1]
terms = vectorizer.get_feature_names()
for i in range(true_k):
    print("Cluster %d:" % i),
    for ind in order_centroids[i, :10]:
        print(' %s' % terms[ind]),
    print

print("\n")
print("Prediction")

Top terms per cluster:
Cluster 0:
 come
 don
 sir
 red
 ve
 think
 ship
 oh
 know
 got
Cluster 1:
 ll
 right
 worry
 cover
 got
 ve
 ship
 escape
 better
 time
Cluster 2:
 luke
 going
 pull
 come
 force
 long
 know
 try
 just
 let
Cluster 3:
 like
 wait
 don
 dead
 looks
 hit
 look
 minute
 want
 got


Prediction


In this portion of code we can see that the word "falcon" (short for "Milleniuim Falcon") is in the same cluster as the word "ship"

In [47]:
Y = vectorizer.transform(["falcon"])
Z = vectorizer.transform(["ship"])
prediction = model.predict(Y)
prediction1 = model.predict(Z)
print(prediction)
print(prediction1)

[0]
[0]


### Bag of word
We can use the fetaure extraction method from sklearn in order to vectorize our text. Again for semplicity we run it only on the Star Wars IV movie. A bag of word is basically an array of unique words that are present in our text. 

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer 
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(StarWarsIV)
print(vectorizer.get_feature_names())

Since the print above will be huge we can see a more informative things that is it's structure.

In [49]:
print(X.shape)

(6167, 1641)


We can also, insted, use (unique) bigrams as word for our bag.

In [50]:
# This time we use 2-grams:
vectorizer2 = CountVectorizer(analyzer='word', ngram_range=(2, 2))
X2 = vectorizer2.fit_transform(StarWarsIV)
print(vectorizer2.get_feature_names())

['aa twenty', 'ain tmy', 'alive will', 'all powerful', 'anyway luke', 'artoo detoo', 'astro droids', 'bulk cruisers', 'check out', 'damned fool', 'eight seven', 'eight two', 'first class', 'first mate', 'five seven', 'fleet its', 'four one', 'freighter tanker', 'half sized', 'here it', 'human cyborg', 'it just', 'large scale', 'navi computer', 'ninety four', 'obi wan', 'oh five', 'oh two', 'one eight', 'one five', 'one man', 'one one', 'one three', 'one two', 'ray shielded', 'see threepio', 'short circuited', 'six eight', 'sixty five', 'stand by', 'star pilot', 'station set', 'thing she', 'three eight', 'three seven', 'three two', 'together you', 'turbo lasers', 'twenty one', 'twenty three', 'twenty threedegrees', 'two hundred', 'two seven', 'two six', 'tx four', 'weak minded', 'xp 38', 'you remy']


Here we simply vectorize our text using the TF-IDF method

In [ ]:
#TF-IDF
vectorizer = TfidfVectorizer()
X1 = vectorizer.fit_transform(StarWarsIV)
print(vectorizer.get_feature_names())

Again, for semplicity, we can analyse it's shape.

In [52]:
print(X.shape)

(6167, 1641)


In [53]:
print(X.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


### Topic Model
Topic model is a statistical method for discovering the abstract topics that occur in a documents. To do this we will use the package "spacy" particularly suitable in natural language processing or sentimenatl analysis. We will use LDA as topic model which is used to classify text in a document to a particular topic.
First we need to lemmatize our word, stemm it, tokenize it and delete any stopwords.

In [55]:
import spacy
spacy.load('en_core_web_sm')
from spacy.lang.en import English
parser = English()

def tokenize(text):
    lda_tokens = []
    tokens = parser(text)
    for token in tokens:
        if token.orth_.isspace():
            continue
        elif token.like_url:
            lda_tokens.append('URL')
        elif token.orth_.startswith('@'):
            lda_tokens.append('SCREEN_NAME')
        else:
            lda_tokens.append(token.lower_)
    return lda_tokens

In [56]:
from nltk.corpus import wordnet as wn
def get_lemma(word):
    lemma = wn.morphy(word)
    if lemma is None:
        return word
    else:
        return lemma
    
from nltk.stem.wordnet import WordNetLemmatizer
def get_lemma2(word):
    return WordNetLemmatizer().lemmatize(word)

In [57]:
en_stop = set(nltk.corpus.stopwords.words('english'))

In [58]:
def prepare_text_for_lda(text):
    tokens = tokenize(text)
    tokens = [token for token in tokens if len(token) > 4]
    tokens = [token for token in tokens if token not in en_stop]
    tokens = [get_lemma(token) for token in tokens]
    return tokens

Now we need to install gensim that is a library for unsupervised topic model.

In [59]:
pip install -U gensim

Requirement already up-to-date: gensim in c:\users\tompe\anaconda3\lib\site-packages (3.8.3)
Note: you may need to restart the kernel to use updated packages.Requirement already satisfied, skipping upgrade: six>=1.5.0 in c:\users\tompe\anaconda3\lib\site-packages (from gensim) (1.15.0)



In [60]:
text_data = []
with open('SW_EpisodeIVclean.txt') as f:
    for line in f:
        tokens = prepare_text_for_lda(line)
        text_data.append(tokens)

The following cell will create a dictionary which is a mapping between words and their integer ids.

In [61]:
from gensim import corpora
dictionary = corpora.Dictionary(text_data) #StarWarsIV

In [62]:
corpus = [dictionary.doc2bow(text) for text in text_data] # counts the number of occurrences of each distinct word

In [63]:
import pickle
pickle.dump(corpus, open('corpus.pkl', 'wb'))
dictionary.save('dictionary.gensim')

Now we will create our model, an LDA model, with five topics

In [64]:
import gensim
NUM_TOPICS = 5
ldamodel = gensim.models.ldamodel.LdaModel(corpus, num_topics = NUM_TOPICS, id2word=dictionary, passes=15)
ldamodel.save('model5.gensim')

Now we can print each topic with its coherence

In [69]:
topics = ldamodel.print_topics(num_words=6)
for topic in topics:
    print(topic)

(0, '0.025*"going" + 0.022*"think" + 0.016*"blast" + 0.014*"standing" + 0.011*"anything" + 0.010*"friend"')
(1, '0.040*"going" + 0.015*"alderaan" + 0.015*"kenobi" + 0.011*"droid" + 0.011*"talking" + 0.011*"little"')
(2, '0.020*"artoo" + 0.016*"going" + 0.014*"thing" + 0.014*"force" + 0.012*"worry" + 0.011*"would"')
(3, '0.013*"uncle" + 0.012*"power" + 0.011*"biggs" + 0.010*"rebel" + 0.010*"station" + 0.010*"watch"')
(4, '0.055*"right" + 0.023*"threepio" + 0.017*"leader" + 0.015*"think" + 0.014*"could" + 0.013*"father"')


Now we will create the same model but with ten topics

In [71]:
ldamodel = gensim.models.ldamodel.LdaModel(corpus, num_topics = 10, id2word=dictionary, passes=15)
ldamodel.save('model10.gensim')
topics = ldamodel.print_topics(num_words=5)
for topic in topics:
    print(topic)

(0, '0.053*"think" + 0.032*"leader" + 0.021*"blast" + 0.020*"chewie" + 0.018*"could"')
(1, '0.027*"standing" + 0.024*"rebel" + 0.022*"worry" + 0.018*"think" + 0.015*"range"')
(2, '0.044*"force" + 0.016*"computer" + 0.014*"system" + 0.012*"could" + 0.012*"always"')
(3, '0.017*"artoo" + 0.015*"clear" + 0.015*"dangerous" + 0.012*"station" + 0.012*"space"')
(4, '0.096*"going" + 0.072*"right" + 0.017*"station" + 0.017*"fighter" + 0.013*"battle"')
(5, '0.017*"think" + 0.015*"talking" + 0.014*"uncle" + 0.014*"thought" + 0.013*"little"')
(6, '0.035*"threepio" + 0.033*"going" + 0.024*"princess" + 0.024*"coming" + 0.021*"droids"')
(7, '0.023*"father" + 0.016*"detention" + 0.015*"three" + 0.014*"vader" + 0.009*"going"')
(8, '0.036*"kenobi" + 0.026*"anything" + 0.016*"happen" + 0.014*"friend" + 0.014*"great"')
(9, '0.038*"artoo" + 0.022*"would" + 0.021*"enough" + 0.019*"friend" + 0.019*"something"')


We can also analyse the overall topic coherence

In [ ]:
top_topics = ldamodel.top_topics(corpus) #, num_words=20)

# Average topic coherence is the sum of topic coherences of all topics, divided by the number of topics.
avg_topic_coherence = sum([t[1] for t in top_topics]) / 4
print('Average topic coherence: %.4f.' % avg_topic_coherence)

from pprint import pprint
pprint(top_topics)

### Summarisation
Now we will apply summarisation to the IVth Star Wars movie by imposing a maximum of 100 words, but first we need to parser our text (for completeness we read from the beginning the file for each chapter).

In [82]:
from gensim.summarization.summarizer import summarize


In [83]:
from collections import OrderedDict
import numpy as np
import spacy
from spacy.lang.en.stop_words import STOP_WORDS

nlp = spacy.load('en_core_web_sm')

This time we will read it as a string

In [85]:
with open('SW_EpisodeIVclean.txt', 'r') as file:
    data = file.read().replace('\n', '')

#### TextRank
TextRank is an algorithm based on PageRank and is usefull in order to understand the summarization

In [86]:
class TextRank4Keyword():
    """Extract keywords from text"""
    
    def __init__(self):
        self.d = 0.85 # damping coefficient, usually is .85
        self.min_diff = 1e-5 # convergence threshold
        self.steps = 10 # iteration steps
        self.node_weight = None # save keywords and its weight

    
    def set_stopwords(self, stopwords):  
        """Set stop words"""
        for word in STOP_WORDS.union(set(stopwords)):
            lexeme = nlp.vocab[word]
            lexeme.is_stop = True
    
    def sentence_segment(self, doc, candidate_pos, lower):
        """Store those words only in cadidate_pos"""
        sentences = []
        for sent in doc.sents:
            selected_words = []
            for token in sent:
                # Store words only with cadidate POS tag
                if token.pos_ in candidate_pos and token.is_stop is False:
                    if lower is True:
                        selected_words.append(token.text.lower())
                    else:
                        selected_words.append(token.text)
            sentences.append(selected_words)
        return sentences
        
    def get_vocab(self, sentences):
        """Get all tokens"""
        vocab = OrderedDict()
        i = 0
        for sentence in sentences:
            for word in sentence:
                if word not in vocab:
                    vocab[word] = i
                    i += 1
        return vocab
    
    def get_token_pairs(self, window_size, sentences):
        """Build token_pairs from windows in sentences"""
        token_pairs = list()
        for sentence in sentences:
            for i, word in enumerate(sentence):
                for j in range(i+1, i+window_size):
                    if j >= len(sentence):
                        break
                    pair = (word, sentence[j])
                    if pair not in token_pairs:
                        token_pairs.append(pair)
        return token_pairs
        
    def symmetrize(self, a):
        return a + a.T - np.diag(a.diagonal())
    
    def get_matrix(self, vocab, token_pairs):
        """Get normalized matrix"""
        # Build matrix
        vocab_size = len(vocab)
        g = np.zeros((vocab_size, vocab_size), dtype='float')
        for word1, word2 in token_pairs:
            i, j = vocab[word1], vocab[word2]
            g[i][j] = 1
            
        # Get Symmeric matrix
        g = self.symmetrize(g)
        
        # Normalize matrix by column
        norm = np.sum(g, axis=0)
        g_norm = np.divide(g, norm, where=norm!=0) # this is ignore the 0 element in norm
        
        return g_norm

    
    def get_keywords(self, number=10):
        """Print top number keywords"""
        node_weight = OrderedDict(sorted(self.node_weight.items(), key=lambda t: t[1], reverse=True))
        for i, (key, value) in enumerate(node_weight.items()):
            print(key + ' - ' + str(value))
            if i > number:
                break
        
        
    def analyze(self, text, 
                candidate_pos=['NOUN', 'PROPN'], 
                window_size=4, lower=False, stopwords=list()):
        """Main function to analyze text"""
        
        # Set stop words
        self.set_stopwords(stopwords)
        
        # Parse text by spaCy
        doc = nlp(text)
        
        # Filter sentences
        sentences = self.sentence_segment(doc, candidate_pos, lower) # list of list of words
        
        # Build vocabulary
        vocab = self.get_vocab(sentences)
        
        # Get token_pairs from windows
        token_pairs = self.get_token_pairs(window_size, sentences)
        
        # Get normalized matrix
        g = self.get_matrix(vocab, token_pairs)
        
        # Initionlization for weight(pagerank value)
        pr = np.array([1] * len(vocab))
        
        # Iteration
        previous_pr = 0
        for epoch in range(self.steps):
            pr = (1-self.d) + self.d * np.dot(g, pr)
            if abs(previous_pr - sum(pr))  < self.min_diff:
                break
            else:
                previous_pr = sum(pr)

        # Get weight for each node
        node_weight = dict()
        for word, index in vocab.items():
            node_weight[word] = pr[index]
        
        self.node_weight = node_weight

From the next portion of code we can know some "imporant" word in our text which can be usefull for the summarisation process

In [87]:
tr4w = TextRank4Keyword()
tr4w.analyze(data, candidate_pos = ['NOUN', 'PROPN'], window_size=4, lower=False)
tr4w.get_keywords(10)

ship - 6.504885004948206
time - 6.1955890912561875
Luke - 6.1608797582721975
power - 5.805977498614775
sir - 5.662529301043638
station - 5.340396594552676
systems - 3.989081986904476
lot - 3.897116519200681
father - 3.782256009413122
Empire - 3.5678547061732533
Alderaan - 3.451203956231256
unit - 3.3384542258123715


Now we can print our summarisation

In [45]:
print(summarize(data, word_count=100))

Luke, I'm not going to wait for the Empire to draft me into service.
I know, but he's got enough vaporators going to make the place pay off.
I think those new droids are going to work out fine.
You know that little droid is going to cause me a lot of trouble.
I think it is time we demonstrate the full power of this station.Set your course for Princess Leia's home planet of Alderaan.
Look, going good against remotes is one thing.
It's going to be like old times Luke.
Luke, let me know when you're going in.


And indeed, despite the short lenght, we can found almost all the words returned by the TextRank method

## Classification
Now we will use a different dataset. The scope here is to define a classificaion method that is able to classify SMS as SPAM or not (HAM). The result we would have obtained from the previous dataset would not have been relevant.

In [88]:
dataset = pd.read_csv('SPAM text message 20170820 - Data.csv')
dataset.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

Also here is very important to delete any stopwords, convert all the words to lowercase and stemm it (i.e. remove the last part of the word in order to make it like the infinit form the verb). If we forgot to do this we may obtain a very low accuracy in the final model because, basically, it will result in a more complex task for the machine. Here we will use the porter stemmer algorithm.

In [89]:
from nltk.stem import PorterStemmer
nltk.download('stopwords')
stemmer = PorterStemmer()
words = stopwords.words("english")
dataset['cleaned'] = dataset['Message'].apply(lambda x: " ".join([stemmer.stem(i) for i in re.sub("[^a-zA-Z]", " ", x).split() if i not in words]).lower())

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\tompe\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


Now we will vectorize it by using the TF-IDF method by deleting any stopwords

In [90]:
vectorizer = TfidfVectorizer(min_df= 3, stop_words="english", sublinear_tf=True, norm='l2', ngram_range=(1, 2))
final_features = vectorizer.fit_transform(dataset['cleaned']).toarray()
final_features.shape

(5572, 4118)

Finally we can create our model. Note that we choose the logistic regression method because, since dealing with text can be a complex problem for our machines, we prefer a simpler method. Logistic regression basically classify binary dependent variable.
Last but not least, we print the confusion matrix for our model and we obtain a very accurate model, and we know that too accurate model need deeper analysis becuase they may suffer from overfitting.

In [91]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.pipeline import Pipeline
from sklearn.pipeline import FeatureUnion
# FeatureUnion combines two or more pipelines or transformers
# and is very fast!
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.preprocessing import StandardScaler

X = dataset['cleaned']
Y = dataset['Category']
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.30)

pipeline = Pipeline([('vect', vectorizer),
                     ('chi',  SelectKBest(chi2, k=1200)),
                     ('clf', LogisticRegression(random_state=0))])

model = pipeline.fit(X_train, y_train)
with open('LogisticRegression.pickle', 'wb') as f:
    pickle.dump(model, f)

ytest = np.array(y_test)

# confusion matrix and classification report(precision, recall, F1-score)
print(classification_report(ytest, model.predict(X_test)))
print(confusion_matrix(ytest, model.predict(X_test)))

              precision    recall  f1-score   support

         ham       0.97      1.00      0.98      1447
        spam       0.98      0.79      0.88       225

    accuracy                           0.97      1672
   macro avg       0.98      0.89      0.93      1672
weighted avg       0.97      0.97      0.97      1672

[[1444    3]
 [  47  178]]


## Extracting Facts from text
Now we can use the package "spacy" in order to extract fact from text. Here we will use again the Star Wars dataset. We know that, at the beginning of the IVth Star Wars movie, Darth Vader was in search of the Death Star plans aboard the Princess Leils's ship but cannot find them. Now, iff we extract facts about "plans", indeed we see that they are "not aboard this ship!".

In [92]:
import spacy
import textacy.extract
from urllib import request
from bs4 import BeautifulSoup

# Load the large English NLP model
nlp = spacy.load('en_core_web_sm')

In [93]:
def print_facts(text,keyword):
    
    # Parse the document with spaCy
    doc = nlp(text)

    # Extract semi-structured statements
    statements = textacy.extract.semistructured_statements(doc, keyword)

    for statement in statements:
        subject, verb, fact = statement
        print(f" - {fact}")
    return

In [94]:
print_facts(data,"plans")

 - not in the main computer.						
 - not aboard this ship!  
 - back in our hands.						
